import { ResumeContent } from '@/schema/resume';

export function generateLatexResume(data: ResumeContent): string {
  console.log('Generating LaTeX for data:', data);
  
  const escapeLatex = (text: string): string => {
    return text
      .replace(/\\/g, '\\textbackslash{}')
      .replace(/[&%$#_{}~^]/g, '\\$&')
      .replace(/</g, '\\textless{}')
      .replace(/>/g, '\\textgreater{}');
  };

  const formatPhone = (phone: string): string => {
    // Remove all non-digit characters and format
    const digits = phone.replace(/\D/g, '');
    if (digits.length === 10) {
      return `(${digits.slice(0, 3)}) ${digits.slice(3, 6)}-${digits.slice(6)}`;
    }
    return phone;
  };

  const formatSocialLink = (url: string, platform: string): string => {
    if (!url) return '';
    
    // Ensure URL has proper protocol
    let fullUrl = url;
    if (!url.startsWith('https://') && !url.startsWith('http://')) {
      fullUrl = `https://${url}`;
    }
    
    // Validate URL format
    if (platform === 'linkedin' && !fullUrl.includes('linkedin.com/in/')) {
      console.log(`Invalid LinkedIn URL: ${url}`);
      return '';
    }
    if (platform === 'github' && !fullUrl.includes('github.com/')) {
      console.log(`Invalid GitHub URL: ${url}`);
      return '';
    }
    
    // Extract display text (username part)
    let displayText = '';
    if (platform === 'linkedin') {
      const match = fullUrl.match(/linkedin\.com\/in\/([^\/\?#]+)/);
      displayText = match ? `linkedin.com/in/${match[1]}` : fullUrl;
    } else if (platform === 'github') {
      const match = fullUrl.match(/github\.com\/([^\/\?#]+)/);
      displayText = match ? `github.com/${match[1]}` : fullUrl;
    }
    
    return `\\href{${fullUrl}}{\\underline{${displayText}}}`;
  };

  const formatSkills = (skills: Record<string, string[]>): string => {
    const skillLines: string[] = [];
    
    if (skills.languages?.length) {
      skillLines.push(`\\textbf{Languages}{: ${skills.languages.join(', ')}`);
    }
    if (skills.frameworks?.length) {
      skillLines.push(`\\textbf{Frontend}{: ${skills.frameworks.join(', ')}`);
    }
    if (skills.development_tools?.length) {
      skillLines.push(`\\textbf{Tools}{: ${skills.development_tools.join(', ')}`);
    }
    if (skills.libraries?.length) {
      skillLines.push(`\\textbf{Libraries}{: ${skills.libraries.join(', ')}`);
    }
    
    return skillLines.join(' \\\\ ');
  };

  const formatExperience = (experience: any[]): string => {
    if (!experience?.length) return '';
    
    return experience.map(exp => {
      const responsibilities = exp.responsibilities?.map((resp: string) => 
        `\\resumeItem{${escapeLatex(resp)}}`
      ).join('\n        ') || '';
      
      return `    \\resumeSubheading
      {${escapeLatex(exp.position)}}{${escapeLatex(exp.duration)}}
      {${escapeLatex(exp.organization)}}{${escapeLatex(exp.location)}}
      \\resumeItemListStart
        ${responsibilities}
      \\resumeItemListEnd`;
    }).join('\n\n');
  };

  const formatProjects = (projects: any[]): string => {
    if (!projects?.length) return '';
    
    return projects.map(project => {
      const technologies = project.technologies?.join(', ') || '';
      return `      \\resumeProjectHeading
          {${escapeLatex(project.title)}} ${technologies ? `$|$ \\emph{${escapeLatex(technologies)}}` : ''}
          \\resumeItemListStart
            \\resumeItem{${escapeLatex(project.description)}}
          \\resumeItemListEnd`;
    }).join('\n\n');
  };

  const formatEducation = (education: any[]): string => {
    if (!education?.length) return '';
    
    return education.map(edu => 
      `    \\resumeSubheading
      {${escapeLatex(edu.institution)}}{${escapeLatex(edu.location)}}
      {${escapeLatex(edu.degree)}}{${escapeLatex(edu.duration)}}`
    ).join('\n\n');
  };

  const contactInfo = [
    data.phone ? `\\href{tel:${data.phone.replace(/\D/g, '')}}{(${formatPhone(data.phone)})}` : '',
    data.email ? `\\href{mailto:${data.email}}{\\underline{${data.email}}}` : '',
    data.linkedin ? formatSocialLink(data.linkedin, 'linkedin') : '',
    data.github ? formatSocialLink(data.github, 'github') : ''
  ].filter(Boolean).join(' $|$ ');
  
  console.log('Generated contact info:', contactInfo);

  const latexContent = `%-------------------------
% Resume in Latex
% Generated by Regen Resume Generator
% Based off of: https://github.com/sb2nov/resume
% License : MIT
%------------------------

\\documentclass[letterpaper,11pt]{article}

\\usepackage{latexsym}
\\usepackage[empty]{fullpage}
\\usepackage{titlesec}
\\usepackage{marvosym}
\\usepackage[usenames,dvipsnames]{color}
\\usepackage{verbatim}
\\usepackage{enumitem}
\\usepackage[hidelinks]{hyperref}
\\usepackage{fancyhdr}
\\usepackage[english]{babel}
\\usepackage{tabularx}
\\input{glyphtounicode}


%----------FONT OPTIONS----------
% sans-serif
% \\usepackage[sfdefault]{FiraSans}
% \\usepackage[sfdefault]{roboto}
% \\usepackage[sfdefault]{noto-sans}
% \\usepackage[default]{sourcesanspro}

% serif
% \\usepackage{CormorantGaramond}
% \\usepackage{charter}


\\pagestyle{fancy}
\\fancyhf{} % clear all header and footer fields
\\fancyfoot{}
\\renewcommand{\\headrulewidth}{0pt}
\\renewcommand{\\footrulewidth}{0pt}

% Adjust margins
\\addtolength{\\oddsidemargin}{-0.5in}
\\addtolength{\\evensidemargin}{-0.5in}
\\addtolength{\\textwidth}{1in}
\\addtolength{\\topmargin}{-.5in}
\\addtolength{\\textheight}{1.0in}

\\urlstyle{same}

\\raggedbottom
\\raggedright
\\setlength{\\tabcolsep}{0in}

% Sections formatting
\\titleformat{\\section}{
  \\vspace{-4pt}\\scshape\\raggedright\\large
}{}{0em}{}[\\color{black}\\titlerule \\vspace{-5pt}]

% Ensure that generate pdf is machine readable/ATS parsable
\\pdfgentounicode=1

%-------------------------
% Custom commands
\\newcommand{\\resumeItem}[1]{
  \\item\\small{
    {#1 \\vspace{-2pt}}
  }
}

\\newcommand{\\resumeSubheading}[4]{
  \\vspace{-2pt}\\item
    \\begin{tabular*}{0.97\\textwidth}[t]{l@{\\extracolsep{\\fill}}r}
      \\textbf{#1} & #2 \\\\
      \\textit{\\small#3} & \\textit{\\small #4} \\\\
    \\end{tabular*}\\vspace{-7pt}
}

\\newcommand{\\resumeSubSubheading}[2]{
    \\item
    \\begin{tabular*}{0.97\\textwidth}{l@{\\extracolsep{\\fill}}r}
      \\textit{\\small#1} & \\textit{\\small #2} \\\\
    \\end{tabular*}\\vspace{-7pt}
}

\\newcommand{\\resumeProjectHeading}[2]{
    \\item
    \\begin{tabular*}{0.97\\textwidth}{l@{\\extracolsep{\\fill}}r}
      \\small#1 & #2 \\\\
    \\end{tabular*}\\vspace{-7pt}
}

\\newcommand{\\resumeSubItem}[1]{\\resumeItem{#1}\\vspace{-4pt}}

\\renewcommand\\labelitemii{$\\vcenter{\\hbox{\\tiny$\\bullet$}}$}

\\newcommand{\\resumeSubHeadingListStart}{\\begin{itemize}[leftmargin=0.15in, label={}]}
\\newcommand{\\resumeSubHeadingListEnd}{\\end{itemize}}
\\newcommand{\\resumeItemListStart}{\\begin{itemize}}
\\newcommand{\\resumeItemListEnd}{\\end{itemize}\\vspace{-5pt}}

%-------------------------------------------
%%%%%%  RESUME STARTS HERE  %%%%%%%%%%%%%%%%%%%%%%%%%%%%


\\begin{document}

%----------HEADING----------
\\begin{center}
    \\textbf{\\Large \\scshape ${escapeLatex(data.name)}} \\\\ \\vspace{4pt}
    \\small ${contactInfo}
\\end{center}


%-------------ABOUT SECTION--------------
\\section{${escapeLatex(data.summary.split('.')[0] || 'PROFESSIONAL SUMMARY')}}
\\begin{itemize}[leftmargin=0.15in, label={}]
    \\small{\\item{${escapeLatex(data.summary)}}}
\\end{itemize}


%-----------PROGRAMMING SKILLS-----------
\\section{Technical Skills}
 \\begin{itemize}[leftmargin=0.15in, label={}]
    \\small{\\item{
     ${formatSkills(data.technical_skills)}
    }}
 \\end{itemize}


%-------------------------------------------
%-----------EXPERIENCE-----------
\\section{Experience}
  \\resumeSubHeadingListStart

${formatExperience(data.experience)}

  \\resumeSubHeadingListEnd



%-----------PROJECTS-----------
\\section{Projects}
    \\resumeSubHeadingListStart
${formatProjects(data.projects)}
    \\resumeSubHeadingListEnd



%-----------EDUCATION-----------
\\section{Education}
  \\resumeSubHeadingListStart
${formatEducation(data.education)}
  \\resumeSubHeadingListEnd

${data.certifications && data.certifications.length > 0 ? `
%-----------CERTIFICATIONS-----------
\\section{Certifications}
  \\resumeSubHeadingListStart
    ${data.certifications.map(cert => `\\item ${escapeLatex(cert)}`).join('\n    ')}
  \\resumeSubHeadingListEnd
` : ''}

%
\\end{document}`;

  return latexContent;
} 