import type { ResumeSchemaType } from "@/schema/resume";

export function generateLatexResume(data: ResumeSchemaType): string {
	const escapeLatex = (text: string): string => {
		return text
			.replace(/\\/g, "\\textbackslash{}")
			.replace(/[&%$#_{}~^]/g, "\\$&")
			.replace(/</g, "\\textless{}")
			.replace(/>/g, "\\textgreater{}");
	};

	const formatPhone = (phone: string): string => {
		// Remove all non-digit characters and format
		const digits = phone.replace(/\D/g, "");
		if (digits.length === 10) {
			return `(${digits.slice(0, 3)}) ${digits.slice(3, 6)}-${digits.slice(6)}`;
		}
		return phone;
	};

	const formatSocialLink = (username: string, platform: string): string => {
		if (!username) return "";

		// Construct full URL from username
		let fullUrl = "";
		let displayText = "";

		if (platform === "linkedin") {
			fullUrl = `https://linkedin.com/in/${username}`;
			displayText = `linkedin.com/in/${username}`;
		} else if (platform === "github") {
			fullUrl = `https://github.com/${username}`;
			displayText = `github.com/${username}`;
		}

		return `\\href{${fullUrl}}{\\underline{${displayText}}}`;
	};

	const formatSkills = (skills: Record<string, string[]>): string => {
		const skillLines: string[] = [];

		if (skills.languages?.length) {
			skillLines.push(`\\textbf{Languages}{: ${skills.languages.join(", ")} }`);
		} else {
			skillLines.push(`\\textbf{Languages}{: }`);
		}
		if (skills.frameworks?.length) {
			skillLines.push(
				`\\textbf{Frameworks}{: ${skills.frameworks.join(", ")} }`,
			);
		} else {
			skillLines.push(`\\textbf{Frameworks}{: }`);
		}
		if (skills.development_tools?.length) {
			skillLines.push(
				`\\textbf{Development Tools}{: ${skills.development_tools.join(", ")} }`,
			);
		} else {
			skillLines.push(`\\textbf{Development Tools}{: }`);
		}
		if (skills.libraries?.length) {
			skillLines.push(`\\textbf{Libraries}{: ${skills.libraries.join(", ")} }`);
		} else {
			skillLines.push(`\\textbf{Libraries}{: }`);
		}

		return skillLines.join(" \\\\ ");
	};

	const formatExperience = (experience: any[]): string => {
		if (!experience?.length) return "";

		return experience
			.map((exp) => {
				const responsibilities =
					exp.responsibilities
						?.map(
							(resp: string) => `        \\resumeItem{${escapeLatex(resp)}}`,
						)
						.join("\n") || "";

				return `    \\resumeSubheading
      {${escapeLatex(exp.position)}}{${escapeLatex(exp.duration)}}
      {${escapeLatex(exp.organization)}}{${escapeLatex(exp.location)}}
      \\resumeItemListStart
${responsibilities}
      \\resumeItemListEnd`;
			})
			.join("\n\n");
	};

	const formatProjects = (projects: any[]): string => {
		if (!projects?.length) return "";

		return projects
			.map((project) => {
				const technologies = project.technologies?.join(", ") || "";
				const projectYear = project.year || new Date().getFullYear().toString();

				// Format project title with URL if available
				let projectTitle = escapeLatex(project.title);
				if (project.url) {
					projectTitle = `\\href{${project.url}}{\\underline{\\textbf{${escapeLatex(project.title)}}}}`;
				}

				return `      \\resumeProjectHeading
          { ${projectTitle} ${technologies ? `$|$ \\emph{${escapeLatex(technologies)}}` : ""}}{${projectYear}}
          \\resumeItemListStart
            \\resumeItem{${escapeLatex(project.description)}}
          \\resumeItemListEnd`;
			})
			.join("\n\n");
	};

	const formatEducation = (education: any[]): string => {
		if (!education?.length) return "";

		return education
			.map(
				(edu) =>
					`    \\resumeSubheading
      {${escapeLatex(edu.institution)}}{${escapeLatex(edu.location)}}
      {${escapeLatex(edu.degree)}}{${escapeLatex(edu.duration)}}`,
			)
			.join("\n\n");
	};

	const contactInfo = [
		data.phone
			? `\\href{tel:${data.phone.replace(/\D/g, "")}}{(${formatPhone(data.phone)})}`
			: "",
		data.email
			? `\\href{mailto:${data.email}}{\\underline{${data.email}}}`
			: "",
		data.linkedin ? formatSocialLink(data.linkedin, "linkedin") : "",
		data.github ? formatSocialLink(data.github, "github") : "",
	]
		.filter(Boolean)
		.join(" $|$ ");

	const latexContent = `%-------------------------
% Resume in Latex
% Generated by Regen Resume Generator
% Based off of: https://github.com/sb2nov/resume
% License : MIT
%------------------------

\\documentclass[letterpaper,11pt]{article}

\\usepackage{latexsym}
\\usepackage[empty]{fullpage}
\\usepackage{titlesec}
\\usepackage{marvosym}
\\usepackage[usenames,dvipsnames]{color}
\\usepackage{verbatim}
\\usepackage{enumitem}
\\usepackage[hidelinks]{hyperref}
\\usepackage{fancyhdr}
\\usepackage[english]{babel}
\\usepackage{tabularx}
\\input{glyphtounicode}


%----------FONT OPTIONS----------
% sans-serif
% \\usepackage[sfdefault]{FiraSans}
% \\usepackage[sfdefault]{roboto}
% \\usepackage[sfdefault]{noto-sans}
% \\usepackage[default]{sourcesanspro}

% serif
% \\usepackage{CormorantGaramond}
% \\usepackage{charter}


\\pagestyle{fancy}
\\fancyhf{} % clear all header and footer fields
\\fancyfoot{}
\\renewcommand{\\headrulewidth}{0pt}
\\renewcommand{\\footrulewidth}{0pt}

% Adjust margins
\\addtolength{\\oddsidemargin}{-0.5in}
\\addtolength{\\evensidemargin}{-0.5in}
\\addtolength{\\textwidth}{1in}
\\addtolength{\\topmargin}{-.5in}
\\addtolength{\\textheight}{1.0in}

\\urlstyle{same}

\\raggedbottom
\\raggedright
\\setlength{\\tabcolsep}{0in}

% Sections formatting
\\titleformat{\\section}{
  \\vspace{-4pt}\\scshape\\raggedright\\large
}{}{0em}{}[\\color{black}\\titlerule \\vspace{-5pt}]

% Ensure that generate pdf is machine readable/ATS parsable
\\pdfgentounicode=1

%-------------------------
% Custom commands
\\newcommand{\\resumeItem}[1]{
  \\item\\small{
    {#1 \\vspace{-2pt}}
  }
}

\\newcommand{\\resumeSubheading}[4]{
  \\vspace{-2pt}\\item
    \\begin{tabular*}{0.97\\textwidth}[t]{l@{\\extracolsep{\\fill}}r}
      \\textbf{#1} & #2 \\\\
      \\textit{\\small#3} & \\textit{\\small #4} \\\\
    \\end{tabular*}\\vspace{-7pt}
}

\\newcommand{\\resumeSubSubheading}[2]{
    \\item
    \\begin{tabular*}{0.97\\textwidth}{l@{\\extracolsep{\\fill}}r}
      \\textit{\\small#1} & \\textit{\\small #2} \\\\
    \\end{tabular*}\\vspace{-7pt}
}

\\newcommand{\\resumeProjectHeading}[2]{
    \\item
    \\begin{tabular*}{0.97\\textwidth}{l@{\\extracolsep{\\fill}}r}
      \\small#1 & #2 \\\\
    \\end{tabular*}\\vspace{-7pt}
}

\\newcommand{\\resumeSubItem}[1]{\\resumeItem{#1}\\vspace{-4pt}}

\\renewcommand\\labelitemii{$\\vcenter{\\hbox{\\tiny$\\bullet$}}$}

\\newcommand{\\resumeSubHeadingListStart}{\\begin{itemize}[leftmargin=0.15in, label={}]}
\\newcommand{\\resumeSubHeadingListEnd}{\\end{itemize}}
\\newcommand{\\resumeItemListStart}{\\begin{itemize}}
\\newcommand{\\resumeItemListEnd}{\\end{itemize}\\vspace{-5pt}}

%-------------------------------------------
%%%%%%  RESUME STARTS HERE  %%%%%%%%%%%%%%%%%%%%%%%%%%%%


\\begin{document}

%----------HEADING----------
\\begin{center}
    \\textbf{\\Large \\scshape ${escapeLatex(data.name)}} \\\\ \\vspace{4pt}
    \\small ${contactInfo}
\\end{center}


%-------------ABOUT SECTION--------------
\\section{SUMMARY}
\\begin{itemize}[leftmargin=0.15in, label={}]
    \\small{\\item{${escapeLatex(data.summary)}}}
\\end{itemize}


%-----------PROGRAMMING SKILLS-----------
\\section{TECHNICAL SKILLS}
 \\begin{itemize}[leftmargin=0.15in, label={}]
    \\small{\\item{
     ${formatSkills(data.technical_skills)}
    }}
 \\end{itemize}


%-------------------------------------------
%-----------EXPERIENCE-----------
\\section{EXPERIENCE}
  \\resumeSubHeadingListStart

${formatExperience(data.experience)}

  \\resumeSubHeadingListEnd


%-----------PROJECTS-----------
\\section{PROJECTS}
    \\resumeSubHeadingListStart
${formatProjects(data.projects)}
    \\resumeSubHeadingListEnd


%-----------EDUCATION-----------
\\section{EDUCATION}
  \\resumeSubHeadingListStart
${formatEducation(data.education)}
  \\resumeSubHeadingListEnd

${
	data.certifications && data.certifications.length > 0
		? `
%-----------CERTIFICATIONS-----------
\\section{CERTIFICATIONS}
  \\resumeSubHeadingListStart
    ${data.certifications.map((cert) => `\\item ${escapeLatex(cert)}`).join("\n    ")}
  \\resumeSubHeadingListEnd
`
		: ""
}

%
\\end{document}`;

	return latexContent;
}
